package ProiectFinal.UIgui;

import ProiectFinal.Data.Agenda;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.JWindow;
import ProiectFinal.Data.Agenda.CriteriuOrdonare;
import ProiectFinal.Data.Contact;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.time.format.DateTimeFormatter;



public class GUI extends javax.swing.JFrame implements Serializable {

    private DefaultListModel<Contact> model;
    private DefaultComboBoxModel filtre = new DefaultComboBoxModel(new String[]{"NR_FIX", "NR_MOBIL", "NASCUTI_ZI_CURENTA", "NASCUTI_LUNA_CURENTA", "PERSONALIZAT"});
    private DefaultComboBoxModel ordoneaza = new DefaultComboBoxModel(new String[]{"DUPA_NUME", "DUPA_PRENUME", "DUPA_VARSTA", "DUPA_TELEFON"});
    private final String codInregistrare = "1234";
    
    public String filtru;
    public Agenda a = new Agenda();
    

    ImageIcon imaginea;
    String[] imagini = {"Resurse/1.png", "Resurse/2.png", "Resurse/3.png", "Resurse/4.png", "Resurse/5.png"};
    int index = 0;
    JWindow window = new JWindow();

    ActionListener task = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (index == imagini.length) {
                index = 0;
            } else {
                imaginea = new ImageIcon(getClass().getResource(imagini[index]));
                poza.setIcon(imaginea);
                index++;
            }
        }
    };

    javax.swing.Timer timer = new javax.swing.Timer(1000, task);

    private void actualizeazaModel(List m) {
        model.clear();
        for (int i = 0; i < m.size(); i++) {
            Contact k = (Contact) m.get(i);
            model.addElement(k);
        }
    }

    public GUI() {
        this.task = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (index == 1) {
                    index = 0;
                } else {
                    imaginea = new ImageIcon(getClass().getResource(imagini[index]));
                    poza.setIcon(imaginea);
                    index++;
                }
            }
        };

        initComponents();
        
        model = new DefaultListModel<Contact>();
        cbf.setModel(filtre);
        cbo.setModel(ordoneaza);
        bAdaugare.setEnabled(false);
        bStergere.setEnabled(false);
        bEditeaza.setEnabled(false);
        bFiltreaza.setEnabled(false);
        bOrdoneaza.setEnabled(false);
        cbf.setEnabled(false);
        cbo.setEnabled(false);
        tf2.setEnabled(false);
        mbSalvare.setEnabled(false);
        timer.start();
        setCenterForDialogs();
        
    }

    private void setCenterForDialogs(){
        Despre.pack();
        Despre.setLocationRelativeTo(null);
        dialog_iesire.pack();
        dialog_iesire.setLocationRelativeTo(null);
        Adaugare_contacte.pack();
        Adaugare_contacte.setLocationRelativeTo(null);
        Stergere.pack();
        Stergere.setLocationRelativeTo(null);
        Modificare_contacte.pack();
        Modificare_contacte.setLocationRelativeTo(null);
        Inregistrare.pack();
        Inregistrare.setLocationRelativeTo(null);
    }
    
    private void clearForm() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adaugare_contacte = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bAdauga = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Stergere = new javax.swing.JDialog();
        nu = new javax.swing.JButton();
        da = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        element_desters = new javax.swing.JLabel();
        Modificare_contacte = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        bModifica = new javax.swing.JButton();
        dialog_iesire = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fc = new javax.swing.JFileChooser();
        fc2 = new javax.swing.JFileChooser();
        Despre = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Inregistrare = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        parola = new javax.swing.JTextField();
        bInregistreaza = new javax.swing.JButton();
        bine_venit = new javax.swing.JDialog();
        incarca = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label_filtrare = new javax.swing.JLabel();
        label_ordonare = new javax.swing.JLabel();
        label_filtru = new javax.swing.JLabel();
        cbf = new javax.swing.JComboBox<>();
        cbo = new javax.swing.JComboBox<>();
        tf2 = new javax.swing.JTextField();
        bFiltreaza = new javax.swing.JButton();
        bOrdoneaza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        l = new javax.swing.JList<>();
        bAdaugare = new javax.swing.JButton();
        bStergere = new javax.swing.JButton();
        bEditeaza = new javax.swing.JButton();
        poza = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_fisier = new javax.swing.JMenu();
        mbSalvare = new javax.swing.JMenu();
        mbDeschidere = new javax.swing.JMenu();
        mbIesire = new javax.swing.JMenu();
        menu_ajutor = new javax.swing.JMenu();
        mbInregistrare = new javax.swing.JMenuItem();
        mbDespre = new javax.swing.JMenuItem();

        Adaugare_contacte.setResizable(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume");

        jLabel2.setText("Prenume");

        jLabel3.setText("Data nastere");

        jLabel4.setText("Telefon");

        bAdauga.setText("Adauga");
        bAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaActionPerformed(evt);
            }
        });

        jLabel5.setText("ADAUGARE  CONTACTE");

        javax.swing.GroupLayout Adaugare_contacteLayout = new javax.swing.GroupLayout(Adaugare_contacte.getContentPane());
        Adaugare_contacte.getContentPane().setLayout(Adaugare_contacteLayout);
        Adaugare_contacteLayout.setHorizontalGroup(
            Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Adaugare_contacteLayout.createSequentialGroup()
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4))))
                .addContainerGap())
            .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel5)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        Adaugare_contacteLayout.setVerticalGroup(
            Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(bAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.getAccessibleContext().setAccessibleName("Adaugare Contact");

        Stergere.setTitle("Sterge contact");
        Stergere.setAlwaysOnTop(true);
        Stergere.setMinimumSize(new java.awt.Dimension(200, 400));
        Stergere.setModal(true);
        Stergere.setResizable(false);
        Stergere.setSize(new java.awt.Dimension(200, 400));

        nu.setText("NU");
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });

        da.setText("DA");
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });

        jLabel6.setText("Sunteti siguri ca doriti sa stergeti elementul selectat?");

        javax.swing.GroupLayout StergereLayout = new javax.swing.GroupLayout(Stergere.getContentPane());
        Stergere.getContentPane().setLayout(StergereLayout);
        StergereLayout.setHorizontalGroup(
            StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StergereLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StergereLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(nu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(element_desters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StergereLayout.setVerticalGroup(
            StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StergereLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(element_desters)
                .addGap(18, 18, 18)
                .addGroup(StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(da)
                    .addComponent(nu))
                .addContainerGap())
        );

        Modificare_contacte.setResizable(false);

        jLabel7.setText("Modificare Contact");

        jLabel8.setText("Nume nou:");

        jLabel9.setText("Prenume nou:");

        jLabel10.setText("Data nastere noua:");

        jLabel11.setText("Telefon nou:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        bModifica.setText("Modifica");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Modificare_contacteLayout = new javax.swing.GroupLayout(Modificare_contacte.getContentPane());
        Modificare_contacte.getContentPane().setLayout(Modificare_contacteLayout);
        Modificare_contacteLayout.setHorizontalGroup(
            Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Modificare_contacteLayout.createSequentialGroup()
                                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(37, 37, 37)
                                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField5)))
                            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                                        .addComponent(bModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))))
                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Modificare_contacteLayout.setVerticalGroup(
            Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bModifica)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        dialog_iesire.setAlwaysOnTop(true);
        dialog_iesire.setBackground(new java.awt.Color(255, 255, 255));
        dialog_iesire.setResizable(false);
        dialog_iesire.setSize(new java.awt.Dimension(400, 200));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Doriti sa parasiti aplicatia?");

        jButton1.setText("DA");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NU");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_iesireLayout = new javax.swing.GroupLayout(dialog_iesire.getContentPane());
        dialog_iesire.getContentPane().setLayout(dialog_iesireLayout);
        dialog_iesireLayout.setHorizontalGroup(
            dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_iesireLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialog_iesireLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jLabel13))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        dialog_iesireLayout.setVerticalGroup(
            dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_iesireLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Despre.setResizable(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(2);
        jTextArea2.setText("Aplicatie: Agenda Telefonica \nAutor: Petre Alexandru\nAn: 2020");
        jTextArea2.setToolTipText("");
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout DespreLayout = new javax.swing.GroupLayout(Despre.getContentPane());
        Despre.getContentPane().setLayout(DespreLayout);
        DespreLayout.setHorizontalGroup(
            DespreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        DespreLayout.setVerticalGroup(
            DespreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        Inregistrare.setResizable(false);

        jLabel12.setText("INTRODUCE PAROLA");

        bInregistreaza.setText("Inregistreaza");
        bInregistreaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInregistreazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InregistrareLayout = new javax.swing.GroupLayout(Inregistrare.getContentPane());
        Inregistrare.getContentPane().setLayout(InregistrareLayout);
        InregistrareLayout.setHorizontalGroup(
            InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InregistrareLayout.createSequentialGroup()
                .addGroup(InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InregistrareLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel12)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(InregistrareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bInregistreaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parola))))
                .addContainerGap())
        );
        InregistrareLayout.setVerticalGroup(
            InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InregistrareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bInregistreaza)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        bine_venit.setResizable(false);

        incarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bine_venitLayout = new javax.swing.GroupLayout(bine_venit.getContentPane());
        bine_venit.getContentPane().setLayout(bine_venitLayout);
        bine_venitLayout.setHorizontalGroup(
            bine_venitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bine_venitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bine_venitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(incarca, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bine_venitLayout.setVerticalGroup(
            bine_venitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bine_venitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incarca, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda Telefonica");
        setResizable(false);

        label_filtrare.setText("Filtrare");

        label_ordonare.setText("Ordonare");

        label_filtru.setText("Filtru personalizat");

        cbf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NUMAR_FIX", "NUMAR_MOBIL", "NASCUTI_ZI_CURENTA", "NASCUTI_LUNA_CURENTA", "PERSONALIZAT" }));
        cbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfActionPerformed(evt);
            }
        });

        cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DUPA_NUME", "DUPA_PRENUME", "DUPA_VARSTA", "DUPA_DATA" }));

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        bFiltreaza.setText("Filtreaza");
        bFiltreaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltreazaActionPerformed(evt);
            }
        });

        bOrdoneaza.setText("Ordoneaza");
        bOrdoneaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdoneazaActionPerformed(evt);
            }
        });

        l.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(l);

        bAdaugare.setText("Adauga contact");
        bAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugareActionPerformed(evt);
            }
        });

        bStergere.setText("Sterge contact selectat");
        bStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergereActionPerformed(evt);
            }
        });

        bEditeaza.setText("Editare contact selectat");
        bEditeaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditeazaActionPerformed(evt);
            }
        });

        poza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        menu_fisier.setText("Fisiere");

        mbSalvare.setText("Salvare");
        mbSalvare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbSalvareMouseClicked(evt);
            }
        });
        menu_fisier.add(mbSalvare);

        mbDeschidere.setText("Deschidere");
        mbDeschidere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbDeschidereMouseClicked(evt);
            }
        });
        menu_fisier.add(mbDeschidere);

        mbIesire.setText("Iesire");
        mbIesire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbIesireMouseClicked(evt);
            }
        });
        menu_fisier.add(mbIesire);

        jMenuBar1.add(menu_fisier);

        menu_ajutor.setText("Ajutor");

        mbInregistrare.setText("Inregistrare");
        mbInregistrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbInregistrareActionPerformed(evt);
            }
        });
        menu_ajutor.add(mbInregistrare);

        mbDespre.setText("Despre");
        mbDespre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDespreActionPerformed(evt);
            }
        });
        menu_ajutor.add(mbDespre);

        jMenuBar1.add(menu_ajutor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_ordonare)
                            .addComponent(label_filtrare))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bOrdoneaza, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_filtru)
                                .addGap(18, 18, 18)
                                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bFiltreaza, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bAdaugare, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(bStergere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(183, 183, 183)
                        .addComponent(bEditeaza, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(poza, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_filtru)
                        .addComponent(cbf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bFiltreaza))
                    .addComponent(label_filtrare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ordonare)
                    .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOrdoneaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAdaugare)
                    .addComponent(bStergere)
                    .addComponent(bEditeaza))
                .addGap(18, 18, 18)
                .addComponent(poza, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbIesireActionPerformed(java.awt.event.ActionEvent evt) {
        dialog_iesire.setVisible(true);
        dialog_iesire.pack();
    }


    private void cbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfActionPerformed

    private void bAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugareActionPerformed
        // TODO add your handling code here:
        Adaugare_contacte.setVisible(true);
        Adaugare_contacte.pack();
    }//GEN-LAST:event_bAdaugareActionPerformed

    private void bStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergereActionPerformed
        // TODO add your handling code here:
        Stergere.setVisible(true);
        Stergere.pack();
        Stergere.setSize(400, 200);
    }//GEN-LAST:event_bStergereActionPerformed

    private void bEditeazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditeazaActionPerformed
        // TODO add your handling code here:

        Modificare_contacte.setVisible(true);
        Modificare_contacte.pack();

        try {
            int selectedIndex = l.getSelectedIndex();
            Contact c = (Contact) a.Contacte.get(selectedIndex);

            DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("d.MM.yyyy");

            String nume = c.getNume();
            String prenume = c.getPrenume();
            String data = c.getData_nastere().format(dateFormat);
            String telefon = c.getTelefon().toString();

            jTextField5.setText(nume);
            jTextField6.setText(prenume);
            jTextField7.setText(data);
            jTextField8.setText(telefon);

        } catch (RuntimeException re) {
            System.out.println(re.getMessage());
        }
    }//GEN-LAST:event_bEditeazaActionPerformed

    private void bFiltreazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltreazaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cbf.getSelectedIndex();

        if (selectedIndex == 0) { //dupa numar fix;
            a.filtreazaNrFix();
            List contacte_filtrate = a.contacte_functie(true);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 1) { //dupa numar mobil;
            a.filtreazaNrMobil();
            List contacte_filtrate = a.contacte_functie(true);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 2) { //dupa nascuti in ziua asta;
            a.filtreazaNascutiAstazi();
            List contacte_filtrate = a.contacte_functie(true);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 3) { //dupa numar luna;
            a.filtreazaNascutiLunaCurenta();
            List contacte_filtrate = a.contacte_functie(true);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 4) { //personalizat
            filtru = tf2.getText();
            a.filtreazaPersonalizat(filtru);
            List contacte_filtrate = a.contacte_functie(true);
            actualizeazaModel(contacte_filtrate);
    }//GEN-LAST:event_bFiltreazaActionPerformed
    }

    private void bOrdoneazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdoneazaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cbo.getSelectedIndex();

        if (selectedIndex == 0) { //dupa nume
            a.Ordoneaza(CriteriuOrdonare.DUPA_NUME);
            List contacte_filtrate = a.contacte_functie(false);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 1) { //dupa prenume
            a.Ordoneaza(CriteriuOrdonare.DUPA_PRENUME);
            List contacte_filtrate = a.contacte_functie(false);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 2) { //dupa varsta
            a.Ordoneaza(CriteriuOrdonare.DUPA_VARSTA);
            List contacte_filtrate = a.contacte_functie(false);
            actualizeazaModel(contacte_filtrate);
        }

        if (selectedIndex == 3) { //dupa telefon
            a.Ordoneaza(CriteriuOrdonare.DUPA_TELEFON);
            List contacte_filtrate = a.contacte_functie(false);
            actualizeazaModel(contacte_filtrate);
        }
    }//GEN-LAST:event_bOrdoneazaActionPerformed

    private void mbInregistrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbInregistrareActionPerformed
        // TODO add your handling code here:
        Inregistrare.setVisible(true);
        Inregistrare.pack();
    }//GEN-LAST:event_mbInregistrareActionPerformed

    private void mbDespreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDespreActionPerformed
        // TODO add your handling code here:
        Despre.setVisible(true);
        Despre.pack();
    }//GEN-LAST:event_mbDespreActionPerformed

    private void bAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaActionPerformed

        try {
            String nume = jTextField1.getText();
            String prenume = jTextField2.getText();
            String data = jTextField3.getText();
            String telefon = jTextField4.getText();
            
            a.Adauga(nume, prenume, data, telefon);
            l.setModel(model);
            actualizeazaModel(a.Contacte);
            Adaugare_contacte.setVisible(false);
            clearForm();
        } catch (RuntimeException e) {
            if (e.getMessage().equals("NUMELE SAU PRENUMELE PREA SCURT!")) {
                JOptionPane.showMessageDialog(this, "NUMELE SAU PRENUMELE PREA SCURT!");
            }
            if (e.getMessage().equals("contactul exista!")) {
                JOptionPane.showMessageDialog(this, "CONTACTUL EXISTA DEJA IN LISTA DE CONTACTE!");
            }
            if (e.getMessage().contains("parse")) {
                JOptionPane.showMessageDialog(this, "PROBLEMA LA FORMATUL DATEI zz/ll/yyyy!");
            }
            if (e.getMessage().contains("Numaru nu are 10 cifre...")) {
                JOptionPane.showMessageDialog(this, "NUMARUL NU ARE 10 CIFRE!");
            }
            if (e.getMessage().contains("Numarul nu incepe cu 07,02 sau 03!")) {
                JOptionPane.showMessageDialog(this, "NUMARUL DE TELEFON NU INCEPE CU 07,02 sau 03!");
            }
        }
    }//GEN-LAST:event_bAdaugaActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed

        try {
            int selectedIndex;
            
            String nume = jTextField5.getText();
            String prenume = jTextField6.getText();
            String data = jTextField7.getText();
            String telefon = jTextField8.getText();
            
            selectedIndex = l.getSelectedIndex();
            Contact c = (Contact) a.Contacte.get(selectedIndex);
            
            a.Modifica(nume, prenume, data, telefon, c);
            actualizeazaModel(a.Contacte);
            Modificare_contacte.setVisible(false);
            clearForm();
        } catch (RuntimeException e) {
            if (e.getMessage().equals("NUMELE SAU PRENUMELE PREA SCURT!")) {
                JOptionPane.showMessageDialog(this, "NUMELE SAU PRENUMELE PREA SCURT!");
            }
            if (e.getMessage().equals("contactul exista!")) {
                JOptionPane.showMessageDialog(this, "CONTACTUL EXISTA DEJA IN LISTA DE CONTACTE!");
            }
            if (e.getMessage().contains("parse")) {
                JOptionPane.showMessageDialog(this, "PROBLEMA LA FORMATUL DATEI zz/ll/yyyy!");
            }
            if (e.getMessage().contains("Numaru nu are 10 cifre...")) {
                JOptionPane.showMessageDialog(this, "NUMARUL NU ARE 10 CIFRE!");
            }
            if (e.getMessage().contains("Numarul nu incepe cu 07,02 sau 03!")) {
                JOptionPane.showMessageDialog(this, "NUMARUL DE TELEFON NU INCEPE CU 07,02 sau 03!");
            }
        }
    }//GEN-LAST:event_bModificaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dialog_iesire.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bInregistreazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInregistreazaActionPerformed
        String parolaa;
        parolaa = parola.getText();
        
        if (parolaa.equals(codInregistrare)) {
            bAdaugare.setEnabled(true);
            bStergere.setEnabled(true);
            bEditeaza.setEnabled(true);
            bFiltreaza.setEnabled(true);
            bOrdoneaza.setEnabled(true);
            cbf.setEnabled(true);
            cbo.setEnabled(true);
            tf2.setEnabled(true);
            mbSalvare.setEnabled(true);

            Inregistrare.setVisible(false);
            mbInregistrare.setEnabled(false);
            timer.stop();
            poza.setVisible(false);
            JOptionPane.showMessageDialog(this, "PAROLA CORECTA!");

        } else {
            JOptionPane.showMessageDialog(this, "PAROLA GRESITA!");
        }
    }//GEN-LAST:event_bInregistreazaActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        int selectedIndex = l.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
            a.Stergere((Contact) a.Contacte.get(selectedIndex));
            Stergere.setVisible(false);
        }
    }//GEN-LAST:event_daActionPerformed

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        Stergere.setVisible(false);
    }//GEN-LAST:event_nuActionPerformed

    private void mbSalvareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbSalvareMouseClicked
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            Timer t = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    try {
                        FileOutputStream fos = new FileOutputStream(f);
                        ObjectOutputStream oos = new ObjectOutputStream(fos);
                        oos.writeObject(a.Contacte);
                        oos.close();
                        fos.close();
                    } catch (IOException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            t.schedule(task, 0, 30000);
        }
    }//GEN-LAST:event_mbSalvareMouseClicked

    private void mbIesireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbIesireMouseClicked
        dialog_iesire.setVisible(true);
    }//GEN-LAST:event_mbIesireMouseClicked

    private void mbDeschidereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbDeschidereMouseClicked
        int val = fc.showOpenDialog(this);
        if (val == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            Timer t = new Timer();
            TimerTask task = new TimerTask() {
                @Override
                public void run() {

                    try {
                        try (FileInputStream fis = new FileInputStream(f)) {
                            ObjectInputStream ois = new ObjectInputStream(fis);
                            List contacte;

                            contacte = (List) ois.readObject();
                            l.setModel(model);
                            a.Contacte = contacte;
                            actualizeazaModel(contacte);

                            ois.close();
                            fis.close();

                        }
                    } catch (IOException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            };
            t.schedule(task, 0, 30000);
        }
    }//GEN-LAST:event_mbDeschidereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Adaugare_contacte;
    private javax.swing.JDialog Despre;
    private javax.swing.JDialog Inregistrare;
    private javax.swing.JDialog Modificare_contacte;
    private javax.swing.JDialog Stergere;
    private javax.swing.JButton bAdauga;
    private javax.swing.JButton bAdaugare;
    private javax.swing.JButton bEditeaza;
    private javax.swing.JButton bFiltreaza;
    private javax.swing.JButton bInregistreaza;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton bOrdoneaza;
    private javax.swing.JButton bStergere;
    private javax.swing.JDialog bine_venit;
    private javax.swing.JComboBox<String> cbf;
    private javax.swing.JComboBox<String> cbo;
    private javax.swing.JButton da;
    private javax.swing.JDialog dialog_iesire;
    private javax.swing.JLabel element_desters;
    private javax.swing.JFileChooser fc;
    private javax.swing.JFileChooser fc2;
    private javax.swing.JLabel incarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JList<Contact> l;
    private javax.swing.JLabel label_filtrare;
    private javax.swing.JLabel label_filtru;
    private javax.swing.JLabel label_ordonare;
    private javax.swing.JMenu mbDeschidere;
    private javax.swing.JMenuItem mbDespre;
    private javax.swing.JMenu mbIesire;
    private javax.swing.JMenuItem mbInregistrare;
    private javax.swing.JMenu mbSalvare;
    private javax.swing.JMenu menu_ajutor;
    private javax.swing.JMenu menu_fisier;
    private javax.swing.JButton nu;
    private javax.swing.JTextField parola;
    private javax.swing.JLabel poza;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
